name: Build project

on:
  workflow_dispatch:
    inputs:
      targetPlatform:
        description: 'Platform to build'
        type: choice
        options:
          - StandaloneWindows
          - Android
          - iOS
        default: StandaloneWindows

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ github.event.inputs.targetPlatform }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ github.event.inputs.targetPlatform }}
          restore-keys: Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ github.event.inputs.targetPlatform }}

      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ github.event.inputs.targetPlatform }}
          path: build/${{ github.event.inputs.targetPlatform }}
